# Configuration variables and their default values
# Set these in application top-level build makefile.

# The backend for I/O (e.g. 'hwuart', 'swuart', etc.)
# See 'ls console_*.c' for available implementations.
LIBIO_BACKEND ?= hwuart
